export const WEATHER_REQUESTING = 'WEATHER_REQUESTING';
export const WEATHER_SUCCESS = 'WEATHER_SUCCESS';
export const WEATHER_ERROR = 'WEATHER_ERROR';
export const SET_WEATHERLIST = 'SET_WEATHERLIST';
