export const FORECAST_REQUESTING = 'FORECAST_REQUESTING';
export const FORECAST_SUCCESS = 'FORECAST_SUCCESS';
export const FORECAST_ERROR = 'FORECAST_ERROR';
export const SET_FORECASTLIST = 'SET_FORECASTLIST';
