export const CARETEAM_REQUESTING = 'CARETEAM_REQUESTING';
export const CARETEAM_SUCCESS = 'CARETEAM_SUCCESS';
export const CARETEAM_ERROR = 'CARETEAM_ERROR';

export const CARETEAM_CHANGE_STATUS_REQUESTING = 'CARETEAM_CHANGE_STATUS_REQUESTING';
export const CARETEAM_CHANGE_STATUS_SUCCESS = 'CARETEAM_CHANGE_STATUS_SUCCESS';
export const CARETEAM_CHANGE_STATUS_ERROR = 'CARETEAM_CHANGE_STATUS_ERROR';