export const SIGNUP_START = 'SIGNUP_START';
export const SIGNUP_REQUESTING = 'SIGNUP_REQUESTING';
export const SIGNUP_SUCCESS = 'SIGNUP_SUCCESS';
export const SIGNUP_ERROR = 'SIGNUP_ERROR';
export const REGISTER_USER = 'REGISTER_USER';
